/// Theme-specific world names for each of the 35 campaign worlds.
///
/// Each theme has its own atmosphere and naming convention:
///   - Sky Heroes: aviation, flight, sky, clouds, stars
///   - Enchanted Kingdom: magic, forests, castles, creatures
///   - Explorer Quest: maps, jungles, treasure, discovery

const Map<String, List<String>> themeWorldNames = {
  'sky_heroes': [
    'Cloudbreak Runway',
    'Thunder Hangar',
    'Solar Watchtower',
    'The Gale Corridor',
    'Starfall Outpost',
    'Moonrise Airfield',
    'Storm Chaser Bay',
    'Driftwind Docks',
    'Ember Jet Summit',
    'The Frozen Altitude',
    'Sapphire Skyport',
    'Windshear Heights',
    'The Iron Propeller',
    'Coral Cloud Harbor',
    'Sandstorm Airstrip',
    'The Verdant Flyover',
    'Obsidian Cockpit',
    'Lantern Flight Path',
    'The Painted Horizon',
    'Cloudtop Command',
    'The Sunken Airship',
    'Blossom Glider Gate',
    'Stormwatch Lookout',
    'The Amber Altitude',
    'Frostfire Launchpad',
    'The Golden Jetstream',
    'Shadow Wing Glade',
    'Skybridge Control',
    'The Velvet Altitude',
    'Dragonfly Squadron',
    'The Wandering Jet',
    'Prism Propeller Peak',
    'The Silent Beacon',
    'Evergreen Airfield',
    'The Final Skyline',
  ],
  'enchanted_kingdom': [
    'The Whispering Meadow',
    'Crystal Caverns',
    'Sunstone Valley',
    'The Echo Cave',
    'Starfall Ridge',
    'Moonlit Marsh',
    'Thornwood Thicket',
    'Driftwood Shores',
    'Ember Peak',
    'The Frozen Quill',
    'Sapphire Lagoon',
    'Windmill Heights',
    'The Iron Library',
    'Coral Reef Kingdom',
    'Sandstorm Citadel',
    'The Verdant Canopy',
    'Obsidian Fortress',
    'Lantern Falls',
    'The Painted Desert',
    'Cloudtop Spire',
    'The Sunken Archive',
    'Blossom Gate',
    'Stormwatch Tower',
    'The Amber Ruins',
    'Frostfire Hollow',
    'The Golden Bazaar',
    'Shadowfern Glade',
    'Skybridge Summit',
    'The Velvet Depths',
    'Dragonfly Isles',
    'The Wandering Path',
    'Prism Peak',
    'The Silent Lighthouse',
    'Evergreen Sanctum',
    'The Final Chapter',
  ],
  'explorer_quest': [
    'Basecamp Cove',
    'Compass Falls',
    'Jungle Crossing',
    'The Echo Gorge',
    'Starmap Ridge',
    'Moonstone Swamp',
    'Thornvine Trail',
    'Driftwood Inlet',
    'Ember Canyon',
    'The Frozen Passage',
    'Sapphire Springs',
    'Windcatcher Bluffs',
    'The Iron Bridge',
    'Coral Tide Grotto',
    'Sandstorm Oasis',
    'The Verdant Ravine',
    'Obsidian Outpost',
    'Lantern Creek',
    'The Painted Plateau',
    'Cloudtop Lookout',
    'The Sunken Temple',
    'Blossom Trailhead',
    'Stormwatch Camp',
    'The Amber Dig Site',
    'Frostfire Glacier',
    'The Golden Market',
    'Shadowfern Jungle',
    'Skybridge Crossing',
    'The Velvet Cavern',
    'Dragonfly Delta',
    'The Wandering River',
    'Prism Cliff',
    'The Silent Shipwreck',
    'Evergreen Basecamp',
    'The Last Frontier',
  ],
};

/// Get the world name for a specific theme and world index.
/// Falls back to Enchanted Kingdom names if theme not found.
String getThemedWorldName(String themeKey, int worldIndex) {
  final names = themeWorldNames[themeKey] ?? themeWorldNames['enchanted_kingdom']!;
  if (worldIndex < 0 || worldIndex >= names.length) return 'Unknown World';
  return names[worldIndex];
}
